name: Docker Series Builds

on: [push]

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
      
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    
    - name: docker build csharp
      run: |
        docker build ./c# -t aimvector/csharp:1.0.0

    - name: docker build nodejs
      run: |
        docker build ./nodejs -t aimvector/nodejs:1.0.0

    - name: docker build python
      run: |
        docker build ./python -t aimvector/python:1.0.0
