name: Docker Series Builds

on: [push]

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
            
    - name: docker build csharp
      run: |
        docker build ./c# -t aimvector/csharp:1.0.0

    - name: docker build nodejs
      run: |
        docker build ./nodejs -t aimvector/nodejs:1.0.0

    - name: docker build python
      run: |
        docker build ./python -t aimvector/python:1.0.0
